# Generated by Django 5.2.17 on 2026-09-05 04:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='Batch number')),
                ('planned_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Planned, kg')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Actual, kg')),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('RESERVED', 'Materials reserved'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=16)),
                ('planned_date', models.DateField(default=django.utils.timezone.localdate)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('output_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_output', to='inventory.warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.product')),
                ('recipe_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='recipes.recipeversion')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_source', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Production batch',
                'verbose_name_plural': 'Production batches',
                'ordering': ('-planned_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BatchConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='inventory.stocklot')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='production.productionbatch')),
            ],
            options={
                'verbose_name': 'Material consumption',
                'verbose_name_plural': 'Material consumption',
            },
        ),
        migrations.CreateModel(
            name='ProductionOverhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overheads', to='production.productionbatch')),
            ],
            options={
                'verbose_name': 'Overhead',
                'verbose_name_plural': 'Overheads',
            },
        ),
    ]
