# Generated by Django 5.2.17 on 2026-09-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('purpose', models.CharField(choices=[('PRODUCTION', 'Production'), ('SALES', 'Sales')], max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CONSUMED', 'Consumed'), ('RELEASED', 'Released')], default='ACTIVE', max_length=16)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_code', models.CharField(max_length=64, unique=True, verbose_name='Internal lot code')),
                ('supplier_batch_code', models.CharField(blank=True, max_length=64, verbose_name='Supplier batch code')),
                ('document', models.CharField(blank=True, max_length=64, verbose_name='Goods receipt note')),
                ('received_at', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Unit cost, UAH')),
            ],
            options={
                'verbose_name': 'Stock lot',
                'verbose_name_plural': 'Stock lots',
                'ordering': ('expiry_date', 'received_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_type', models.CharField(choices=[('IN', 'Receipt'), ('OUT', 'Issue'), ('WRITE_OFF', 'Write-off'), ('TRANSFER', 'Transfer'), ('ADJUST', 'Stock take')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.CharField(blank=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Stock move',
                'verbose_name_plural': 'Stock moves',
                'ordering': ('-occurred_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ('code',),
            },
        ),
    ]
