# Generated by Django 5.2.17 on 2026-09-05 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sku', models.CharField(max_length=32, unique=True, verbose_name='SKU')),
                ('unit', models.CharField(choices=[('KG', 'kg'), ('G', 'g'), ('L', 'l'), ('PCS', 'pcs'), ('M', 'm')], default='KG', max_length=8)),
                ('target_margin', models.DecimalField(decimal_places=2, default=33.3, max_digits=5, verbose_name='Target margin, %')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Finished product',
                'verbose_name_plural': 'Finished products',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tax_id', models.CharField(blank=True, max_length=16, verbose_name='Tax ID')),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sku', models.CharField(max_length=32, unique=True, verbose_name='SKU')),
                ('category', models.CharField(choices=[('RAW', 'Raw material'), ('SPICE', 'Spices'), ('CASING', 'Casing'), ('PACKAGING', 'Packaging'), ('OTHER', 'Other')], default='RAW', max_length=16)),
                ('unit', models.CharField(choices=[('KG', 'kg'), ('G', 'g'), ('L', 'l'), ('PCS', 'pcs'), ('M', 'm')], default='KG', max_length=8)),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('shelf_life_days', models.PositiveIntegerField(default=0, verbose_name='Shelf life, days')),
                ('is_active', models.BooleanField(default=True)),
                ('default_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='catalog.supplier')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ('name',),
            },
        ),
    ]
