# Generated by Django 5.2.17 on 2026-09-05 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recipe', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
            },
        ),
        migrations.CreateModel(
            name='RecipeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=16)),
                ('valid_from', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('yield_min', models.DecimalField(decimal_places=2, default=98, max_digits=5, verbose_name='Yield norm, min %')),
                ('yield_max', models.DecimalField(decimal_places=2, default=99, max_digits=5, verbose_name='Yield norm, max %')),
                ('notes', models.TextField(blank=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Recipe version',
                'verbose_name_plural': 'Recipe versions',
                'ordering': ('-valid_from', '-version'),
                'unique_together': {('recipe', 'version')},
            },
        ),
        migrations.CreateModel(
            name='RecipeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.CharField(choices=[('PERCENT', '% of batch weight'), ('PER_100KG', 'per 100 kg')], default='PERCENT', max_length=16)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_lines', to='catalog.material')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='recipes.recipeversion')),
            ],
            options={
                'verbose_name': 'Recipe line',
                'verbose_name_plural': 'Recipe lines',
                'unique_together': {('version', 'material')},
            },
        ),
    ]
